<?php

/**
 * @file
 * Contains admission_program.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function admission_program_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the admission_program module.
    case 'help.page.admission_program':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This module is for different programs like ug,pg,etc') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function admission_program_theme() {
  return [
    'admission_program' => [
      'render element' => 'children',
    ],
  ];
}
