<?php

/**
 * @file
 * Contains legal_forms1.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function legal_forms1_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the legal_forms1 module.
    case 'help.page.legal_forms1':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Legal forms is module for forms of site') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function legal_forms1_theme() {
  return [
    'legal_forms1' => [
      'render element' => 'children',
    ],
  ];
}
